version: "3.8"

services:
  nginx:
    image: nginx:1.19
    container_name: testinn-nginx
    ports:
      - 80:80
    networks:
      - common
    volumes:
      - ./frontend/:/app/
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    working_dir: /app/
    depends_on:
      - php
      - node
    restart: unless-stopped

  php:
    build:
      context: docker/php
    container_name: testinn-php
    networks:
      - common
    volumes:
      - ./backend/:/app/
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - memcached
    restart: unless-stopped

  composer:
    image: composer:1.10.10
    container_name: testinn-composer
    networks:
      - common
    volumes:
      - ./backend/:/app/
    working_dir: /app

  memcached:
    image: memcached:1.6.6
    container_name: testinn-memcached
    ports:
      - ${MEMCACHED_PORT}:11211
    networks:
      - common
    restart: unless-stopped

  node:
    build:
      context: docker/node
    container_name: testinn-node
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - common
    volumes:
      - ./frontend/:/app/
    working_dir: /app
    restart: unless-stopped

networks:
  common:
